{{ $name := "node" }}
{{ $fullName := printf "%s-%s" .Release.Name $name }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  {{- if .Values.frontendIp }}
  type: LoadBalancer
  loadBalancerIp: {{ .Values.frontendIp }}
  {{- end }}
  selector:
    name: {{ $fullName }}
  ports:
    - protocol: TCP
      port: 80