{{ $name := "node" }}
{{ $fullName := printf "%s-%s" .Release.Name $name }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-subnet: "{{ .Values.sv.env }}-crm-static"
spec:
  {{- if .Values.frontendIp }}
  type: LoadBalancer
  loadBalancerIp: {{ .Values.frontendIp }}
  {{- end }}
  selector:
    name: {{ $fullName }}
  ports:
    - protocol: TCP
      port: 80